### PR TITLE
Move react-native-ffmeg.podspec to root directory of project

### PR DESCRIPTION
**Pull request by DaleWebb**
In order for the auto-installation of pods to work for iOS, the `podspec` must be in the root directory and not `ios/`.

### CODE REVIEW

**Comment by DaleWebb** [comment]
Closes #118

**Comment by tanersener** [comment]
Do you have a documentation reference about this?

**Comment by DaleWebb** [comment]
> Do you have a documentation reference about this?

Unfortunately not.

The only thing I can find is this snapshot test: https://github.com/brodybits/create-react-native-module/blob/5829e0573fe71c66ab7c61600f45abc7d5e47d05/tests/with-injection/create/with-example/with-defaults/__snapshots__/create-with-example-with-defaults.test.js.snap#L425 
 from the third-party tool for creating native modules as recommended by the RN docs: https://reactnative.dev/docs/native-modules-setup

**Comment by tanersener** [comment]
I can confirm this PR fixes #118. But I can't accept PRs against `master`. Can you open it against `development`? So I can publish a new release with this change?

**Comment by DaleWebb** [comment]
Superceded by #139

**Comment by tanersener** [comment]
Thanks

**Pull request closed without merging**
